## Netlify build settings
[build]
  publish = "_site"
  command = "eleventy"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    ".cache" # Remote Asset Cache
  ]

## Cache control for CSS files
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    cache-control = '''
    public,
    max-age=1209600'''

## Opt out of Google's FLoC
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

## Special page redirects
[[redirects]]
  from = "/design"
  to = "/designs"
[[redirects]]
  from = "/shirts"
  to = "/designs"
[[redirects]]
  from = "/posters"
  to = "/designs"
[[redirects]]
  from = "/art"
  to = "/designs"
[[redirects]]
  from = "/follow/"
  to = "/follow.rss"
  status = 301
  force = true

## Error 404 redirects
[[redirects]]
  from = "/fr/*"
  to = "/fr/404.html"
  status = 404

[[redirects]]
  from = "/da/*"
  to = "/da/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404