module.exports = {
	title: 'chriskirknielsen',
	url: 'https://chriskirknielsen.com',
	repo: 'https://github.com/chriskirknielsen/chriskirknielsen.com',
	author: {
		name: 'Christopher Kirk-Nielsen',
		shortname: 'Chris',
		email: 'chriskirknielsen@gmail.com',
		twitter: 'ckirknielsen',
		mastodon: 'chriskirknielsen',
		mastodonInstance: 'mastodon.social',
	},
	tweetArchiveUrl: 'https://tweets.chriskirknielsen.com/',
	copyrightStart: 1992,
	currentYear: new Date().getFullYear(),
	defaultLocale: 'en',
	locales: { en: 'English', fr: 'Français', da: 'Dansk' },
	merch: {
		TeePublic: 'https://www.teepublic.com/user/chriskirknielsen/',
		RedBubble: 'https://www.redbubble.com/people/ckirknielsen/shop',
		Society6: 'https://society6.com/chriskirknielsen',
		DesignByHumans: 'https://www.designbyhumans.com/shop/chriskirknielsen/',
		CottonBureau: 'https://cottonbureau.com/people/state-of-js',
	},
};
